"""init

Revision ID: f61d6e89f97d
Revises: 
Create Date: 2020-07-18 10:16:03.651586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61d6e89f97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_review_stars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建此条记录的用户id'),
    sa.Column('review_id', sa.Integer(), nullable=False, comment='点赞的评论 id'),
    sa.Column('on', sa.Boolean(), nullable=True, comment='是否点赞（考虑取消点赞的情况）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_id', name='unique_user_review_star'),
    comment='给清单评论的点赞记录'
    )
    op.create_index(op.f('ix_checklist_review_stars_deleted_at'), 'checklist_review_stars', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_checklist_review_stars_review_id'), 'checklist_review_stars', ['review_id'], unique=False)
    op.create_index(op.f('ix_checklist_review_stars_user_id'), 'checklist_review_stars', ['user_id'], unique=False)
    op.create_table('checklist_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建此条记录的用户id'),
    sa.Column('checklist_id', sa.Integer(), nullable=False, comment='对应的清单id'),
    sa.Column('detail', sa.String(length=512), nullable=True, comment='详情，为空时表示简单打卡'),
    sa.Column('star_count', sa.Integer(), nullable=True, comment='点赞数目'),
    sa.PrimaryKeyConstraint('id'),
    comment='给清单的评论'
    )
    op.create_index(op.f('ix_checklist_reviews_checklist_id'), 'checklist_reviews', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_reviews_deleted_at'), 'checklist_reviews', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_checklist_reviews_user_id'), 'checklist_reviews', ['user_id'], unique=False)
    op.create_table('checklist_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建此场景的用户id'),
    sa.Column('description', sa.String(length=256), nullable=False, comment='场景描述'),
    sa.PrimaryKeyConstraint('id'),
    comment='场景、场合、某个具体案例、过程'
    )
    op.create_index(op.f('ix_checklist_scenes_deleted_at'), 'checklist_scenes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_checklist_scenes_user_id'), 'checklist_scenes', ['user_id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建此条检查项的用户id'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='场景/场合/案例/过程的id'),
    sa.Column('description', sa.String(length=256), nullable=False, comment='检查项描述'),
    sa.Column('checked_count', sa.Integer(), nullable=False, comment='被确认的个数，考虑到并发，这里只是参考值'),
    sa.Column('last_review_id', sa.Integer(), nullable=True, comment='最后一个评论的id，考虑到并发，这里只是一个参考值'),
    sa.PrimaryKeyConstraint('id'),
    comment='清单'
    )
    op.create_index(op.f('ix_checklists_deleted_at'), 'checklists', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_checklists_scene_id'), 'checklists', ['scene_id'], unique=False)
    op.create_index(op.f('ix_checklists_user_id'), 'checklists', ['user_id'], unique=False)
    op.create_table('kv_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('key', sa.String(length=64), nullable=False, comment='键值'),
    sa.Column('value', sa.String(length=512), nullable=True, comment='具体的值'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    comment='key-value配置项'
    )
    op.create_index(op.f('ix_kv_configs_deleted_at'), 'kv_configs', ['deleted_at'], unique=False)
    op.create_table('tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('display_name', sa.String(length=256), nullable=False, comment='标签展示名'),
    sa.Column('slug', sa.String(length=256), nullable=False, comment='标签跳转路径'),
    sa.Column('location', sa.String(length=256), nullable=False, comment='标签位置'),
    sa.PrimaryKeyConstraint('id'),
    comment='标签及其跳转配置'
    )
    op.create_index(op.f('ix_tabs_deleted_at'), 'tabs', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('nickname', sa.String(length=256), nullable=False, comment='昵称'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='加密后的密码'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='是否验证'),
    sa.Column('token', sa.String(length=64), nullable=False, comment='返回给前端用来鉴权的 token'),
    sa.Column('admin', sa.Boolean(), nullable=False, comment='是否为管理员'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token'),
    comment='用户表'
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tabs_deleted_at'), table_name='tabs')
    op.drop_table('tabs')
    op.drop_index(op.f('ix_kv_configs_deleted_at'), table_name='kv_configs')
    op.drop_table('kv_configs')
    op.drop_index(op.f('ix_checklists_user_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_scene_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_deleted_at'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_checklist_scenes_user_id'), table_name='checklist_scenes')
    op.drop_index(op.f('ix_checklist_scenes_deleted_at'), table_name='checklist_scenes')
    op.drop_table('checklist_scenes')
    op.drop_index(op.f('ix_checklist_reviews_user_id'), table_name='checklist_reviews')
    op.drop_index(op.f('ix_checklist_reviews_deleted_at'), table_name='checklist_reviews')
    op.drop_index(op.f('ix_checklist_reviews_checklist_id'), table_name='checklist_reviews')
    op.drop_table('checklist_reviews')
    op.drop_index(op.f('ix_checklist_review_stars_user_id'), table_name='checklist_review_stars')
    op.drop_index(op.f('ix_checklist_review_stars_review_id'), table_name='checklist_review_stars')
    op.drop_index(op.f('ix_checklist_review_stars_deleted_at'), table_name='checklist_review_stars')
    op.drop_table('checklist_review_stars')
    # ### end Alembic commands ###
