"""scene_add_item_count

Revision ID: 4d76f07c6550
Revises: e28515628c5f
Create Date: 2020-08-23 08:39:33.878007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d76f07c6550'
down_revision = 'e28515628c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_scenes', sa.Column('category', sa.String(length=32), nullable=True, comment='主分类'))
    op.add_column('checklist_scenes', sa.Column('item_count', sa.Integer(), nullable=True, comment='包含的清单数目'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_scenes', 'item_count')
    op.drop_column('checklist_scenes', 'category')
    # ### end Alembic commands ###
