"""reivew_add_index

Revision ID: e28515628c5f
Revises: 5d1fb31597fa
Create Date: 2020-08-19 08:20:27.793440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28515628c5f'
down_revision = '5d1fb31597fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_created_checklist', 'checklist_reviews', ['user_id', 'created_at', 'checklist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_created_checklist', table_name='checklist_reviews')
    # ### end Alembic commands ###
