"""add motto

Revision ID: 44eaec06f26e
Revises: c93138ca34fa
Create Date: 2020-07-21 23:43:02.896396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44eaec06f26e'
down_revision = 'c93138ca34fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mottoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建用户的id'),
    sa.Column('details', sa.String(length=512), nullable=False, comment='场景描述'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='发布者自填的作者或出处'),
    sa.PrimaryKeyConstraint('id'),
    comment='格言'
    )
    op.create_index(op.f('ix_mottoes_deleted_at'), 'mottoes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mottoes_user_id'), 'mottoes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mottoes_user_id'), table_name='mottoes')
    op.drop_index(op.f('ix_mottoes_deleted_at'), table_name='mottoes')
    op.drop_table('mottoes')
    # ### end Alembic commands ###
