"""add_invitation

Revision ID: 5d1fb31597fa
Revises: 44eaec06f26e
Create Date: 2020-07-26 23:09:36.785100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1fb31597fa'
down_revision = '44eaec06f26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='码拥有者的id'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='邀请码'),
    sa.Column('invited_user_id', sa.Integer(), nullable=True, comment='被邀请者的id'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='是否使用'),
    sa.Column('used_time', sa.DateTime(), nullable=True, comment='使用的时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='用户邀请码'
    )
    op.create_index(op.f('ix_user_invitations_deleted_at'), 'user_invitations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_invitations_invited_user_id'), 'user_invitations', ['invited_user_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_user_id'), 'user_invitations', ['user_id'], unique=False)
    op.add_column('checklists', sa.Column('position_order', sa.Integer(), nullable=True, comment='排序的序列号'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'position_order')
    op.drop_index(op.f('ix_user_invitations_user_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_invited_user_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_deleted_at'), table_name='user_invitations')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
